CREATE DATABASE tempalate_base WITH ENCODING 'UTF8' LOCALE_PROVIDER=icu ICU_LOCALE='zh@collation=pinyin' TEMPLATE template0;

-- 禁用外键检查（PostgreSQL 使用事务控制）
BEGIN;

-- ----------------------------
-- Table structure for node
-- ----------------------------
DROP TABLE IF EXISTS node;
CREATE TABLE node (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 使用标准IDENTITY语法
  version INTEGER NOT NULL DEFAULT 0,
  address VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
  updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
  UNIQUE (address)
);

-- 添加列注释（PostgreSQL特有语法）
COMMENT ON TABLE node IS '工作节点';
COMMENT ON COLUMN node.id IS '主键';
COMMENT ON COLUMN node.version IS '版本';
COMMENT ON COLUMN node.address IS 'IP地址';
COMMENT ON COLUMN node.created_at IS '创建时间';
COMMENT ON COLUMN node.updated_at IS '更新时间';

-- 创建普通索引
CREATE INDEX ON node (address);

-- 提交事务
COMMIT;