CREATE DATABASE tempalate_job WITH ENCODING 'UTF8' LOCALE_PROVIDER=icu ICU_LOCALE='zh@collation=pinyin' TEMPLATE template0;

-- 禁用外键检查（PostgreSQL 使用事务控制）
BEGIN;

-- ----------------------------
-- Table structure for job
-- ----------------------------
DROP TABLE IF EXISTS job;
CREATE TABLE job (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 允许手动插入的IDENTITY列
     created_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',  -- PostgreSQL不支持0000-00-00
     updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
     version INTEGER NOT NULL DEFAULT 0,
     tid BIGINT NOT NULL DEFAULT 0,
     user_id BIGINT NOT NULL DEFAULT 0,
     name VARCHAR(255) NOT NULL DEFAULT '',
     status INTEGER NOT NULL DEFAULT 0,
     input JSON NOT NULL,
     output JSON NOT NULL,
     message VARCHAR(255) NOT NULL DEFAULT '',
     checksum VARCHAR(255) NOT NULL DEFAULT '',
     description VARCHAR(255) NOT NULL DEFAULT ''
);

-- 添加表和列注释
COMMENT ON TABLE job IS '任务';
COMMENT ON COLUMN job.id IS 'id';
COMMENT ON COLUMN job.created_at IS '创建时间';
COMMENT ON COLUMN job.updated_at IS '更新时间';
COMMENT ON COLUMN job.version IS '版本';
COMMENT ON COLUMN job.tid IS '租户ID';
COMMENT ON COLUMN job.user_id IS '用户ID';
COMMENT ON COLUMN job.name IS '任务名';
COMMENT ON COLUMN job.status IS '状态, 0: 未开始, 1: 处理中，2: 成功, 3：失败';
COMMENT ON COLUMN job.input IS '任务请求数据';
COMMENT ON COLUMN job.output IS '任务执行结果';
COMMENT ON COLUMN job.message IS '任务结果消息';
COMMENT ON COLUMN job.checksum IS '校验码';
COMMENT ON COLUMN job.description IS '任务描述';

-- 创建索引（PostgreSQL不需要指定ASC和BTREE）
CREATE INDEX idx_status ON job (status);
CREATE INDEX idx_tid_userid ON job (tid, user_id);

-- 提交事务
COMMIT;