CREATE DATABASE tempalate_usercenter WITH ENCODING 'UTF8' LOCALE_PROVIDER=icu ICU_LOCALE='zh@collation=pinyin' TEMPLATE template0;

-- 禁用外键检查（PostgreSQL 使用事务控制）
BEGIN;

-- ----------------------------
-- Table structure for account_wechat
-- ----------------------------
DROP TABLE IF EXISTS account_wechat;
CREATE TABLE account_wechat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
    version INTEGER NOT NULL DEFAULT 0,
    mobile VARCHAR(255) NOT NULL DEFAULT '0',
    union_id VARCHAR(255) NOT NULL DEFAULT '',
    UNIQUE (mobile)
);

COMMENT ON TABLE account_wechat IS '微信账户表';
COMMENT ON COLUMN account_wechat.id IS '主键id';
COMMENT ON COLUMN account_wechat.created_at IS '创建时间';
COMMENT ON COLUMN account_wechat.updated_at IS '更新时间';
COMMENT ON COLUMN account_wechat.version IS '版本号';
COMMENT ON COLUMN account_wechat.mobile IS '用户手机号码';
COMMENT ON COLUMN account_wechat.union_id IS '微信小程序unionId';

-- ----------------------------
-- Table structure for application
-- ----------------------------
DROP TABLE IF EXISTS application;
CREATE TABLE application (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     created_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
     updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
     version INTEGER NOT NULL DEFAULT 0,
     name VARCHAR(255) NOT NULL DEFAULT '',
     app_id VARCHAR(255) NOT NULL DEFAULT '',
     app_secret VARCHAR(255) NOT NULL DEFAULT '',
     UNIQUE (app_id)
);

COMMENT ON TABLE application IS '应用程序表';
COMMENT ON COLUMN application.id IS '主键';
COMMENT ON COLUMN application.created_at IS '创建时间';
COMMENT ON COLUMN application.updated_at IS '更新时间';
COMMENT ON COLUMN application.version IS '版本号';
COMMENT ON COLUMN application.name IS '名称';
COMMENT ON COLUMN application.app_id IS 'AppID';
COMMENT ON COLUMN application.app_secret IS 'App密钥';

-- ----------------------------
-- Table structure for casbin_rule
-- ----------------------------
DROP TABLE IF EXISTS casbin_rule;
CREATE TABLE casbin_rule (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     created_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
     updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
     version INTEGER NOT NULL DEFAULT 0,
     p_type VARCHAR(32) NOT NULL DEFAULT '',
     v0 VARCHAR(64) NOT NULL DEFAULT '',
     v1 VARCHAR(255) NOT NULL DEFAULT '',
     v2 VARCHAR(64) NOT NULL DEFAULT '',
     v3 VARCHAR(255) NOT NULL DEFAULT '',
     v4 VARCHAR(255) NOT NULL DEFAULT '',
     v5 VARCHAR(255) NOT NULL DEFAULT ''
);

CREATE INDEX idx_ptype_v0_v1_v2 ON casbin_rule (p_type, v0, v1, v2);

COMMENT ON TABLE casbin_rule IS '访问规则表';
COMMENT ON COLUMN casbin_rule.id IS '主键';
COMMENT ON COLUMN casbin_rule.created_at IS '创建时间';
COMMENT ON COLUMN casbin_rule.updated_at IS '更新时间';
COMMENT ON COLUMN casbin_rule.version IS '版本号';
COMMENT ON COLUMN casbin_rule.p_type IS 'p_type';
COMMENT ON COLUMN casbin_rule.v0 IS 'v0';
COMMENT ON COLUMN casbin_rule.v1 IS 'v1';
COMMENT ON COLUMN casbin_rule.v2 IS 'v2';
COMMENT ON COLUMN casbin_rule.v3 IS 'v3';
COMMENT ON COLUMN casbin_rule.v4 IS 'v4';
COMMENT ON COLUMN casbin_rule.v5 IS 'v5';

-- ----------------------------
-- Table structure for perm
-- ----------------------------
DROP TABLE IF EXISTS perm;
CREATE TABLE perm (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
      updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
      version INTEGER NOT NULL DEFAULT 0,
      code VARCHAR(255) NOT NULL DEFAULT '',
      UNIQUE (code)
);

COMMENT ON TABLE perm IS '权限表';
COMMENT ON COLUMN perm.id IS '主键';
COMMENT ON COLUMN perm.created_at IS '创建时间';
COMMENT ON COLUMN perm.updated_at IS '更新时间';
COMMENT ON COLUMN perm.version IS '版本';
COMMENT ON COLUMN perm.code IS '权限码';

-- ----------------------------
-- Table structure for role
-- ----------------------------
DROP TABLE IF EXISTS role;
CREATE TABLE role (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
      updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
      version INTEGER NOT NULL DEFAULT 0,
      tid BIGINT NOT NULL DEFAULT 0,
      pid BIGINT NOT NULL DEFAULT 0,
      name VARCHAR(255) NOT NULL DEFAULT '',
      level INTEGER NOT NULL DEFAULT 0,
      code VARCHAR(255) NOT NULL DEFAULT '',
      "group" VARCHAR(255) NOT NULL DEFAULT '',
      UNIQUE (code)
);

CREATE INDEX idx_pid ON role (pid);
CREATE INDEX idx_tid_name ON role (tid, name);

COMMENT ON TABLE role IS '角色表';
COMMENT ON COLUMN role.id IS '主键';
COMMENT ON COLUMN role.created_at IS '创建时间';
COMMENT ON COLUMN role.updated_at IS '更新时间';
COMMENT ON COLUMN role.version IS '版本号';
COMMENT ON COLUMN role.tid IS '租户ID';
COMMENT ON COLUMN role.pid IS '上级角色';
COMMENT ON COLUMN role.name IS '角色名称';
COMMENT ON COLUMN role.level IS '角色级别';
COMMENT ON COLUMN role.code IS '角色值, 角色名:角色级别';
COMMENT ON COLUMN role."group" IS '角色组';  -- 注释也需要转义

-- ----------------------------
-- Table structure for role_widget
-- ----------------------------
DROP TABLE IF EXISTS role_widget;
CREATE TABLE role_widget (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     created_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
     updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
     version INTEGER NOT NULL DEFAULT 0,
     role_id BIGINT NOT NULL DEFAULT 0,
     widget_id BIGINT NOT NULL DEFAULT 0,
     UNIQUE (role_id, widget_id)
);

COMMENT ON TABLE role_widget IS '角色权限关联表';
COMMENT ON COLUMN role_widget.id IS '主键';
COMMENT ON COLUMN role_widget.created_at IS '创建时间';
COMMENT ON COLUMN role_widget.updated_at IS '更新时间';
COMMENT ON COLUMN role_widget.version IS '版本号';
COMMENT ON COLUMN role_widget.role_id IS '角色ID';
COMMENT ON COLUMN role_widget.widget_id IS 'UI组件ID';

-- ----------------------------
-- Table structure for staff_apply
-- ----------------------------
DROP TABLE IF EXISTS staff_apply;
CREATE TABLE staff_apply (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     created_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
     updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
     version INTEGER NOT NULL DEFAULT 0,
     tid BIGINT NOT NULL DEFAULT 0,
     mobile VARCHAR(255) NOT NULL DEFAULT '',
     status INTEGER NOT NULL DEFAULT 0,
     deleted_at TIMESTAMP NULL,
     request JSON NOT NULL
);

CREATE INDEX idx_tid_mobile ON staff_apply (tid, mobile);

COMMENT ON TABLE staff_apply IS '成员申请表';
COMMENT ON COLUMN staff_apply.id IS '主键';
COMMENT ON COLUMN staff_apply.created_at IS '创建时间';
COMMENT ON COLUMN staff_apply.updated_at IS '更新时间';
COMMENT ON COLUMN staff_apply.version IS '版本号';
COMMENT ON COLUMN staff_apply.tid IS '租户ID';
COMMENT ON COLUMN staff_apply.mobile IS '手机号码';
COMMENT ON COLUMN staff_apply.status IS '状态，0：待审核，1：已审核, 2: 已拒绝';
COMMENT ON COLUMN staff_apply.deleted_at IS '删除时间';
COMMENT ON COLUMN staff_apply.request IS '请求信息';

-- ----------------------------
-- Table structure for tenant
-- ----------------------------
DROP TABLE IF EXISTS tenant;
CREATE TABLE tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
    version INTEGER NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL DEFAULT '',
    user_id BIGINT NOT NULL DEFAULT 0,
    data JSON NOT NULL,
    expired_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
    deleted_at TIMESTAMP NULL
);

COMMENT ON TABLE tenant IS '租户表';
COMMENT ON COLUMN tenant.id IS '主键';
COMMENT ON COLUMN tenant.created_at IS '创建时间';
COMMENT ON COLUMN tenant.updated_at IS '更新时间';
COMMENT ON COLUMN tenant.version IS '版本号';
COMMENT ON COLUMN tenant.name IS '名称';
COMMENT ON COLUMN tenant.user_id IS '创建用户ID';
COMMENT ON COLUMN tenant.data IS '额外的数据';
COMMENT ON COLUMN tenant.expired_at IS '过期时间戳';
COMMENT ON COLUMN tenant.deleted_at IS '删除时间戳';

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS "user";
CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
    version INTEGER NOT NULL DEFAULT 0,
    tid BIGINT NOT NULL DEFAULT 0,
    nickname VARCHAR(255) NOT NULL DEFAULT '',
    avatar VARCHAR(255) NOT NULL DEFAULT '',
    mobile VARCHAR(20) NOT NULL DEFAULT '',
    status INTEGER NOT NULL DEFAULT 0,
    pid BIGINT NOT NULL DEFAULT 0,
    rid BIGINT NOT NULL DEFAULT 0,
    data JSON NOT NULL,
    deleted_at TIMESTAMP NULL,
    UNIQUE (tid, mobile, deleted_at)
);

CREATE INDEX idx_tid_pid ON "user" (tid, pid);
CREATE INDEX idx_tid_rid ON "user" (tid, rid);
CREATE INDEX idx_mobile ON "user" (mobile);

COMMENT ON TABLE "user" IS '用户表';
COMMENT ON COLUMN "user".id IS '主键';
COMMENT ON COLUMN "user".created_at IS '创建时间';
COMMENT ON COLUMN "user".updated_at IS '更新时间';
COMMENT ON COLUMN "user".version IS '版本号';
COMMENT ON COLUMN "user".tid IS '租户ID';
COMMENT ON COLUMN "user".nickname IS '昵称';
COMMENT ON COLUMN "user".avatar IS '图像';
COMMENT ON COLUMN "user".mobile IS '手机号码';
COMMENT ON COLUMN "user".status IS '是否可用, 0: 未启用, 1：已启用';
COMMENT ON COLUMN "user".pid IS 'parent user_id, 如果用户为普通用户，则pid表示绑定代理的userId；如果用户为代理，则pid为其上级代理userId';
COMMENT ON COLUMN "user".rid IS '推荐人的userId';
COMMENT ON COLUMN "user".data IS '额外的数据';
COMMENT ON COLUMN "user".deleted_at IS '删除时间';

-- ----------------------------
-- Table structure for user_role
-- ----------------------------
DROP TABLE IF EXISTS user_role;
CREATE TABLE user_role (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   created_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
   updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
   version INTEGER NOT NULL DEFAULT 0,
   user_id BIGINT NOT NULL DEFAULT 0,
   role_id BIGINT NOT NULL DEFAULT 0,
   UNIQUE (user_id, role_id)
);

CREATE INDEX idx_roleid ON user_role (role_id);

COMMENT ON TABLE user_role IS '用户角色表';
COMMENT ON COLUMN user_role.id IS '主键';
COMMENT ON COLUMN user_role.created_at IS '创建时间';
COMMENT ON COLUMN user_role.updated_at IS '更新时间';
COMMENT ON COLUMN user_role.version IS '版本';
COMMENT ON COLUMN user_role.user_id IS '用户id';
COMMENT ON COLUMN user_role.role_id IS '角色id';

-- ----------------------------
-- Table structure for widget
-- ----------------------------
DROP TABLE IF EXISTS widget;
CREATE TABLE widget (
    id BIGINT NOT NULL DEFAULT 0 PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
    updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
    version INTEGER NOT NULL DEFAULT 0,
    pid BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL DEFAULT '',
    title VARCHAR(255) NOT NULL DEFAULT '',
    status INTEGER NOT NULL DEFAULT 0,
    kind INTEGER NOT NULL DEFAULT 0,
    sort INTEGER NOT NULL DEFAULT 0,
    icon VARCHAR(255) NOT NULL DEFAULT '',
    component VARCHAR(255) NOT NULL DEFAULT '',
    path VARCHAR(255) NOT NULL DEFAULT '',
    redirect VARCHAR(255) NOT NULL DEFAULT '',
    meta JSON NOT NULL,
    protected INTEGER NOT NULL DEFAULT 0,
    UNIQUE (name)
);

COMMENT ON TABLE widget IS 'UI组件表';
COMMENT ON COLUMN widget.id IS '主键';
COMMENT ON COLUMN widget.created_at IS '创建时间';
COMMENT ON COLUMN widget.updated_at IS '修改时间';
COMMENT ON COLUMN widget.version IS '版本';
COMMENT ON COLUMN widget.pid IS '上级ID';
COMMENT ON COLUMN widget.name IS '名称';
COMMENT ON COLUMN widget.title IS '显示名称';
COMMENT ON COLUMN widget.status IS '状态';
COMMENT ON COLUMN widget.kind IS '类型';
COMMENT ON COLUMN widget.sort IS '排序';
COMMENT ON COLUMN widget.icon IS '图标';
COMMENT ON COLUMN widget.component IS '地址';
COMMENT ON COLUMN widget.path IS '路径';
COMMENT ON COLUMN widget.redirect IS '重定向地址';
COMMENT ON COLUMN widget.meta IS '元数据';
COMMENT ON COLUMN widget.protected IS '是否受保护, 0: 不受保护，1: 受保护';

-- ----------------------------
-- Table structure for widget_perm
-- ----------------------------
DROP TABLE IF EXISTS widget_perm;
CREATE TABLE widget_perm (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     created_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
     updated_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
     version INTEGER NOT NULL DEFAULT 0,
     widget_id BIGINT NOT NULL DEFAULT 0,
     perm_code VARCHAR(255) NOT NULL DEFAULT '',
     UNIQUE (widget_id, perm_code)
);

COMMENT ON TABLE widget_perm IS '角色权限关联表';
COMMENT ON COLUMN widget_perm.id IS '主键';
COMMENT ON COLUMN widget_perm.created_at IS '创建时间';
COMMENT ON COLUMN widget_perm.updated_at IS '更新时间';
COMMENT ON COLUMN widget_perm.version IS '版本号';
COMMENT ON COLUMN widget_perm.widget_id IS '角色ID';
COMMENT ON COLUMN widget_perm.perm_code IS '权限码';

-- 提交事务
COMMIT;