[project]
    name = "hdmall"
    env = "test"
    gateway_port = 52000

[[repos]]
    name = "config"
    url="https://git.hdget.com/hdmall/common/config.git"

[[repos]]
    name = "proto"
    url="https://git.hdget.com/hdmall/common/proto.git"

[[repos]]
    name = "product"
    url = "https://git.hdget.com/hdmall/backend/product.git"
#
#[[tools]]
#    name = "consul"
#    version = "1.20.5"
#    url_win_release = "https://releases.hashicorp.com/consul/%s/consul_%s_windows_amd64.zip"
#    url_unix_release = "https://releases.hashicorp.com/consul/%s/consul_%s_linux_amd64.zip"