[project]
    name = "hdmall"
    env = "test"
    gateway_port = 52000

[[repos]]
    name = "config"
    url="https://git.hdget.com/hdmall/common/config.git"

[[repos]]
    name = "proto"
    url="https://git.hdget.com/hdmall/common/proto.git"

[[repos]]
    name = "product"
    url = "https://git.hdget.com/hdmall/backend/product.git"